/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package othello_kotlin

import kotlin.test.Test
import kotlin.test.assertNotNull

class OthelloTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = Othello()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
