[package]
name = "othello_rust"
description = "A simple Othello CLI game implementation."
readme = "README.md"
license = "MIT"
version = "1.0.0"
authors = ["Esgrove <esgrove@outlook.com>"]
edition = "2021"

[dependencies]
colored = "2"
env_logger = "0.10.0"
log = "0.4.17"
rand = "0.8.5"
