/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package othello_kotlin

class Othello {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(Othello().greeting)
}
