# https://golangci-lint.run/docs/configuration/
version: "2"

run:
  timeout: 1m

linters:
  default: fast
  enable:
    - lll # Long Line Linter
  disable:
    - depguard
    - dupword
    - funcorder
    - mnd
    - nlreturn
    - wsl
  settings:
    lll:
      line-length: 100
