/*
 * This source file was generated by the Gradle 'init' task
 */
package othello;

import org.junit.Test;

public class MainTest {
    @Test
    public void appHasAGreeting() {
        Main classUnderTest = new Main();
    }
}
