name: TypeScript

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/typescript.yml"
      - "typescript/**.mjs"
      - "typescript/**.ts"
      - "typescript/bun.lock"
      - "typescript/package.json"
  pull_request:
    paths:
      - ".github/workflows/typescript.yml"
      - "typescript/**.mjs"
      - "typescript/**.ts"
      - "typescript/bun.lock"
      - "typescript/package.json"

# Cancel previous runs for PRs but not pushes to main
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: typescript
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            typescript/node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('typescript/bun.lock') }}
          restore-keys: ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Lint
        run: bun lint-check

      - name: Check formatting
        run: bun format-check
